test rule improvement and glide removal
Signed-off-by: Máximo Cuadros <mcuadros@gmail.com>

diff --git a/Makefile.main b/Makefile.main
--- a/Makefile.main
+++ b/Makefile.main
@@ -7,7 +7,6 @@ COMMANDS ?=
 DEPENDENCIES ?=
 PRERUN ?=
 POSTRUN ?=
-RACE_ENABLED ?=
 GOFLAGS ?=
 
 # Dockerfiles to be build, list of pairs file/name, example `Dockerfile:my-image`
@@ -62,6 +61,7 @@ GOCLEAN = $(GOCMD) clean
 GOINSTALL = $(GOCMD) install -v $(GOFLAGS)
 GOGET = $(GOCMD) get -v -t
 GOTEST = $(GOCMD) test -v $(GOFLAGS)
+GOTEST_RACE = $(GOCMD) test -v -race $(GOFLAGS)
 CGO_ENABLED ?= 0
 
 # Coverage
@@ -69,32 +69,17 @@ COVERAGE_REPORT = coverage.txt
 COVERAGE_PROFILE = profile.out
 COVERAGE_MODE = atomic
 
-# Glide
-GLIDE_LOCK = glide.lock
-ifneq ("$(wildcard $(GLIDE_LOCK))","")
-VENDOR_PATH = $(WORKDIR)/vendor
-GLIDE = glide
-DEPENDENCIES += github.com/Masterminds/glide
-else
-VENDOR_PATH =
-endif
-
 PACKAGES = $(shell go list ./... | grep -v '/vendor/')
 
 # Rules
 
 .PHONY: $(DEPENDENCIES) $(PACKAGES) $(COMMANDS) dependencies docker-push docker-push-latest packages test test-coverage pre-run post-run clean
 
+dependencies: $(DEPENDENCIES)
+	$(GOGET) -t ./...; \
+
 $(DEPENDENCIES):
 	$(GOGET) $@/...
-
-$(VENDOR_PATH): $(GLIDE_LOCK)
-	$(GLIDE) install
-
-$(PACKAGES): $(VENDOR_PATH)
-	$(GOGET) $@
-
-dependencies: $(DEPENDENCIES) $(VENDOR_PATH) $(PACKAGES)
 
 docker-validate:
 	@if [ -z "$(DOCKER_USERNAME)" ]; then \
@@ -177,27 +162,29 @@ pre-run:
 test:
 	$(GOTEST) $(PACKAGES)
 
+test-race:
+	$(GOTEST_RACE) $(PACKAGES)
+
 test-coverage:
 	@cd $(WORKDIR); \
 	echo "" > $(COVERAGE_REPORT); \
 	for dir in $(PACKAGES); do \
-		if [ -z $(RACE_ENABLED) ]; then \
-			$(GOTEST) $$dir -coverprofile=$(COVERAGE_PROFILE) -covermode=$(COVERAGE_MODE); \
-		else \
-			$(GOTEST) $$dir -race -coverprofile=$(COVERAGE_PROFILE) -covermode=$(COVERAGE_MODE); \
-		fi; \
-		if [ $$? != 0 ]; then \
-			exit 2; \
-		fi; \
+		$(GOTEST) $$dir -coverprofile=$(COVERAGE_PROFILE) -covermode=$(COVERAGE_MODE); \
 		if [ -f $(COVERAGE_PROFILE) ]; then \
 			cat $(COVERAGE_PROFILE) >> $(COVERAGE_REPORT); \
 			rm $(COVERAGE_PROFILE); \
 		fi; \
-	done; \
+	done || exit 1; \
+
+codecov:
+	@if [ ! -f $(COVERAGE_REPORT) ]; then \
+		echo "Unable to find '$(COVERAGE_REPORT)', execute 'make test-coverage' first."; \
+		exit 1; \
+	fi; \
 	if [[ ! -z "$(CODECOV_TOKEN)" ]] ; then \
 		args="-t $(CODECOV_TOKEN)"; \
 	fi; \
-	bash <(curl -s https://codecov.io/bash) $${args}; \
+	bash <(curl -s https://codecov.io/bash) $${args};
 
 # This target checks if files in a repository have changed after code generation
 # how to generate files is up to project
